Update appium-tests.yml

diff --git a/.github/workflows/appium-tests.yml b/.github/workflows/appium-tests.yml
--- a/.github/workflows/appium-tests.yml
+++ b/.github/workflows/appium-tests.yml
@@ -54,20 +54,39 @@ jobs:
 
       - name: Start emulator
         run: |
-          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
-          adb wait-for-device
-          adb shell settings put global window_animation_scale 0.0
-          adb shell settings put global transition_animation_scale 0.0
-          adb shell settings put global animator_duration_scale 0.0
+          $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -gpu swiftshader_indirect -no-snapshot-save &
+          EMULATOR_PID=$!
+          timeout 5m adb wait-for-device
+          if ps -p $EMULATOR_PID > /dev/null; then
+            echo "Emulator started successfully"
+          else
+            echo "Emulator failed to start"
+            exit 1
+          fi
+          adb shell getprop init.svc.bootanim
 
       - name: Wait for emulator to start
         run: |
           bootanim=""
+          failcounter=0
+          timeout_in_sec=300
           until [[ "$bootanim" =~ "stopped" ]]; do
             bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
-            echo "Waiting for emulator to boot..."
+            if [[ "$bootanim" =~ "stopped" ]]; then
+              echo "Emulator boot animation stopped."
+              break
+            fi
+            ((failcounter += 5))
+            if [[ $failcounter -gt $timeout_in_sec ]]; then
+              echo "Emulator boot process timed out."
+              exit 1
+            fi
+            echo "Waiting for emulator to boot... ($failcounter seconds)"
             sleep 5
           done
+          adb shell settings put global window_animation_scale 0.0
+          adb shell settings put global transition_animation_scale 0.0
+          adb shell settings put global animator_duration_scale 0.0
 
       - name: Copy APK to working directory
         run: cp ./apk/ApiDemos-debug.apk .
